CREATE TABLE address (
    id SERIAL PRIMARY KEY,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    zipcode VARCHAR NOT NULL UNIQUE,
    city VARCHAR NOT NULL,
    state VARCHAR NOT NULL,
    street VARCHAR,
    neighborhood VARCHAR
);